package cn.yx.entity;

import java.util.Date;

public class Demo {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column demo.id
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column demo.author
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    private String author;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column demo.create_time
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column demo.modify_time
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    private Date modifyTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column demo.title
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    private String title;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column demo.content
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    private String content;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column demo.parent
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    private Integer parent;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column demo.url
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    private String url;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column demo.status
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column demo.id
     * @return  the value of demo.id
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column demo.id
     * @param id  the value for demo.id
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column demo.author
     * @return  the value of demo.author
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column demo.author
     * @param author  the value for demo.author
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column demo.create_time
     * @return  the value of demo.create_time
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column demo.create_time
     * @param createTime  the value for demo.create_time
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column demo.modify_time
     * @return  the value of demo.modify_time
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column demo.modify_time
     * @param modifyTime  the value for demo.modify_time
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column demo.title
     * @return  the value of demo.title
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column demo.title
     * @param title  the value for demo.title
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column demo.content
     * @return  the value of demo.content
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column demo.content
     * @param content  the value for demo.content
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column demo.parent
     * @return  the value of demo.parent
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column demo.parent
     * @param parent  the value for demo.parent
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column demo.url
     * @return  the value of demo.url
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column demo.url
     * @param url  the value for demo.url
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column demo.status
     * @return  the value of demo.status
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column demo.status
     * @param status  the value for demo.status
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}