package cn.yx.entity;

import java.util.Date;

public class JcContact {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_contact.id
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_contact.title
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_contact.parent
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    private Integer parent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_contact.img_key
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    private String imgKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_contact.browes
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    private Long browes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_contact.author
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_contact.status
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_contact.create_time
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_contact.lang
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    private Integer lang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_contact.content
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_contact.id
     *
     * @return the value of jc_contact.id
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_contact.id
     *
     * @param id the value for jc_contact.id
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_contact.title
     *
     * @return the value of jc_contact.title
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_contact.title
     *
     * @param title the value for jc_contact.title
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_contact.parent
     *
     * @return the value of jc_contact.parent
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_contact.parent
     *
     * @param parent the value for jc_contact.parent
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_contact.img_key
     *
     * @return the value of jc_contact.img_key
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public String getImgKey() {
        return imgKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_contact.img_key
     *
     * @param imgKey the value for jc_contact.img_key
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void setImgKey(String imgKey) {
        this.imgKey = imgKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_contact.browes
     *
     * @return the value of jc_contact.browes
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public Long getBrowes() {
        return browes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_contact.browes
     *
     * @param browes the value for jc_contact.browes
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void setBrowes(Long browes) {
        this.browes = browes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_contact.author
     *
     * @return the value of jc_contact.author
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_contact.author
     *
     * @param author the value for jc_contact.author
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_contact.status
     *
     * @return the value of jc_contact.status
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_contact.status
     *
     * @param status the value for jc_contact.status
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_contact.create_time
     *
     * @return the value of jc_contact.create_time
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_contact.create_time
     *
     * @param createTime the value for jc_contact.create_time
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_contact.lang
     *
     * @return the value of jc_contact.lang
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public Integer getLang() {
        return lang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_contact.lang
     *
     * @param lang the value for jc_contact.lang
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void setLang(Integer lang) {
        this.lang = lang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_contact.content
     *
     * @return the value of jc_contact.content
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_contact.content
     *
     * @param content the value for jc_contact.content
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }
}