package cn.yx.entity;

public class JcCultureWithBLOBs extends JcCulture {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_culture.content
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_culture.content1
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    private String content1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_culture.content2
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    private String content2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_culture.content
     *
     * @return the value of jc_culture.content
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_culture.content
     *
     * @param content the value for jc_culture.content
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_culture.content1
     *
     * @return the value of jc_culture.content1
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public String getContent1() {
        return content1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_culture.content1
     *
     * @param content1 the value for jc_culture.content1
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void setContent1(String content1) {
        this.content1 = content1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_culture.content2
     *
     * @return the value of jc_culture.content2
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public String getContent2() {
        return content2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_culture.content2
     *
     * @param content2 the value for jc_culture.content2
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void setContent2(String content2) {
        this.content2 = content2;
    }
}