package cn.yx.entity;

import java.util.Date;

public class JcCulture {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_culture.id
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_culture.parent
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    private Integer parent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_culture.title
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_culture.img_key
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    private String imgKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_culture.img_key1
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    private String imgKey1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_culture.img_key2
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    private String imgKey2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_culture.img_key3
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    private String imgKey3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_culture.status
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_culture.create_time
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jc_culture.lang
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    private Integer lang;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_culture.id
     *
     * @return the value of jc_culture.id
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_culture.id
     *
     * @param id the value for jc_culture.id
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_culture.parent
     *
     * @return the value of jc_culture.parent
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_culture.parent
     *
     * @param parent the value for jc_culture.parent
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_culture.title
     *
     * @return the value of jc_culture.title
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_culture.title
     *
     * @param title the value for jc_culture.title
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_culture.img_key
     *
     * @return the value of jc_culture.img_key
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public String getImgKey() {
        return imgKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_culture.img_key
     *
     * @param imgKey the value for jc_culture.img_key
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void setImgKey(String imgKey) {
        this.imgKey = imgKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_culture.img_key1
     *
     * @return the value of jc_culture.img_key1
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public String getImgKey1() {
        return imgKey1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_culture.img_key1
     *
     * @param imgKey1 the value for jc_culture.img_key1
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void setImgKey1(String imgKey1) {
        this.imgKey1 = imgKey1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_culture.img_key2
     *
     * @return the value of jc_culture.img_key2
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public String getImgKey2() {
        return imgKey2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_culture.img_key2
     *
     * @param imgKey2 the value for jc_culture.img_key2
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void setImgKey2(String imgKey2) {
        this.imgKey2 = imgKey2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_culture.img_key3
     *
     * @return the value of jc_culture.img_key3
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public String getImgKey3() {
        return imgKey3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_culture.img_key3
     *
     * @param imgKey3 the value for jc_culture.img_key3
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void setImgKey3(String imgKey3) {
        this.imgKey3 = imgKey3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_culture.status
     *
     * @return the value of jc_culture.status
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_culture.status
     *
     * @param status the value for jc_culture.status
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_culture.create_time
     *
     * @return the value of jc_culture.create_time
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_culture.create_time
     *
     * @param createTime the value for jc_culture.create_time
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jc_culture.lang
     *
     * @return the value of jc_culture.lang
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public Integer getLang() {
        return lang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jc_culture.lang
     *
     * @param lang the value for jc_culture.lang
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void setLang(Integer lang) {
        this.lang = lang;
    }
}