package cn.yx.entity;

import java.util.Date;
import java.util.List;

public class JcHomepage {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jc_homepage.id
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jc_homepage.video_url
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    private String videoUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jc_homepage.introduction
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    private String introduction;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jc_homepage.img_key
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    private String imgKey;
    private String imgUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jc_homepage.media_key
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    private String mediaKey;
    private List<String> mediaUrls;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jc_homepage.media_url
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    private String mediaUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jc_homepage.address
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    private String address;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jc_homepage.phone
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    private String phone;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jc_homepage.mail
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    private String mail;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jc_homepage.status
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    private Integer status;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jc_homepage.create_time
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column jc_homepage.lang
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    private Integer lang;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jc_homepage.id
     * @return  the value of jc_homepage.id
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jc_homepage.id
     * @param id  the value for jc_homepage.id
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jc_homepage.video_url
     * @return  the value of jc_homepage.video_url
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jc_homepage.video_url
     * @param videoUrl  the value for jc_homepage.video_url
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jc_homepage.introduction
     * @return  the value of jc_homepage.introduction
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jc_homepage.introduction
     * @param introduction  the value for jc_homepage.introduction
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jc_homepage.img_key
     * @return  the value of jc_homepage.img_key
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    public String getImgKey() {
        return imgKey;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jc_homepage.img_key
     * @param imgKey  the value for jc_homepage.img_key
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    public void setImgKey(String imgKey) {
        this.imgKey = imgKey;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jc_homepage.media_key
     * @return  the value of jc_homepage.media_key
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    public String getMediaKey() {
        return mediaKey;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jc_homepage.media_key
     * @param mediaKey  the value for jc_homepage.media_key
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    public void setMediaKey(String mediaKey) {
        this.mediaKey = mediaKey;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jc_homepage.media_url
     * @return  the value of jc_homepage.media_url
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    public String getMediaUrl() {
        return mediaUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jc_homepage.media_url
     * @param mediaUrl  the value for jc_homepage.media_url
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    public void setMediaUrl(String mediaUrl) {
        this.mediaUrl = mediaUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jc_homepage.address
     * @return  the value of jc_homepage.address
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jc_homepage.address
     * @param address  the value for jc_homepage.address
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jc_homepage.phone
     * @return  the value of jc_homepage.phone
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jc_homepage.phone
     * @param phone  the value for jc_homepage.phone
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jc_homepage.mail
     * @return  the value of jc_homepage.mail
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jc_homepage.mail
     * @param mail  the value for jc_homepage.mail
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jc_homepage.status
     * @return  the value of jc_homepage.status
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jc_homepage.status
     * @param status  the value for jc_homepage.status
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jc_homepage.create_time
     * @return  the value of jc_homepage.create_time
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jc_homepage.create_time
     * @param createTime  the value for jc_homepage.create_time
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column jc_homepage.lang
     * @return  the value of jc_homepage.lang
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    public Integer getLang() {
        return lang;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column jc_homepage.lang
     * @param lang  the value for jc_homepage.lang
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    public void setLang(Integer lang) {
        this.lang = lang;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public List<String> getMediaUrls() {
        return mediaUrls;
    }

    public void setMediaUrls(List<String> mediaUrls) {
        this.mediaUrls = mediaUrls;
    }
}