package cn.yx.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JcHomepageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jc_homepage
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jc_homepage
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jc_homepage
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_homepage
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public JcHomepageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_homepage
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_homepage
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_homepage
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_homepage
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_homepage
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_homepage
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_homepage
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_homepage
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_homepage
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_homepage
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jc_homepage
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVideoUrlIsNull() {
            addCriterion("video_url is null");
            return (Criteria) this;
        }

        public Criteria andVideoUrlIsNotNull() {
            addCriterion("video_url is not null");
            return (Criteria) this;
        }

        public Criteria andVideoUrlEqualTo(String value) {
            addCriterion("video_url =", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlNotEqualTo(String value) {
            addCriterion("video_url <>", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlGreaterThan(String value) {
            addCriterion("video_url >", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlGreaterThanOrEqualTo(String value) {
            addCriterion("video_url >=", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlLessThan(String value) {
            addCriterion("video_url <", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlLessThanOrEqualTo(String value) {
            addCriterion("video_url <=", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlLike(String value) {
            addCriterion("video_url like", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlNotLike(String value) {
            addCriterion("video_url not like", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlIn(List<String> values) {
            addCriterion("video_url in", values, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlNotIn(List<String> values) {
            addCriterion("video_url not in", values, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlBetween(String value1, String value2) {
            addCriterion("video_url between", value1, value2, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlNotBetween(String value1, String value2) {
            addCriterion("video_url not between", value1, value2, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andIntroductionIsNull() {
            addCriterion("introduction is null");
            return (Criteria) this;
        }

        public Criteria andIntroductionIsNotNull() {
            addCriterion("introduction is not null");
            return (Criteria) this;
        }

        public Criteria andIntroductionEqualTo(String value) {
            addCriterion("introduction =", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotEqualTo(String value) {
            addCriterion("introduction <>", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionGreaterThan(String value) {
            addCriterion("introduction >", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionGreaterThanOrEqualTo(String value) {
            addCriterion("introduction >=", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLessThan(String value) {
            addCriterion("introduction <", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLessThanOrEqualTo(String value) {
            addCriterion("introduction <=", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLike(String value) {
            addCriterion("introduction like", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotLike(String value) {
            addCriterion("introduction not like", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionIn(List<String> values) {
            addCriterion("introduction in", values, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotIn(List<String> values) {
            addCriterion("introduction not in", values, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionBetween(String value1, String value2) {
            addCriterion("introduction between", value1, value2, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotBetween(String value1, String value2) {
            addCriterion("introduction not between", value1, value2, "introduction");
            return (Criteria) this;
        }

        public Criteria andImgKeyIsNull() {
            addCriterion("img_key is null");
            return (Criteria) this;
        }

        public Criteria andImgKeyIsNotNull() {
            addCriterion("img_key is not null");
            return (Criteria) this;
        }

        public Criteria andImgKeyEqualTo(String value) {
            addCriterion("img_key =", value, "imgKey");
            return (Criteria) this;
        }

        public Criteria andImgKeyNotEqualTo(String value) {
            addCriterion("img_key <>", value, "imgKey");
            return (Criteria) this;
        }

        public Criteria andImgKeyGreaterThan(String value) {
            addCriterion("img_key >", value, "imgKey");
            return (Criteria) this;
        }

        public Criteria andImgKeyGreaterThanOrEqualTo(String value) {
            addCriterion("img_key >=", value, "imgKey");
            return (Criteria) this;
        }

        public Criteria andImgKeyLessThan(String value) {
            addCriterion("img_key <", value, "imgKey");
            return (Criteria) this;
        }

        public Criteria andImgKeyLessThanOrEqualTo(String value) {
            addCriterion("img_key <=", value, "imgKey");
            return (Criteria) this;
        }

        public Criteria andImgKeyLike(String value) {
            addCriterion("img_key like", value, "imgKey");
            return (Criteria) this;
        }

        public Criteria andImgKeyNotLike(String value) {
            addCriterion("img_key not like", value, "imgKey");
            return (Criteria) this;
        }

        public Criteria andImgKeyIn(List<String> values) {
            addCriterion("img_key in", values, "imgKey");
            return (Criteria) this;
        }

        public Criteria andImgKeyNotIn(List<String> values) {
            addCriterion("img_key not in", values, "imgKey");
            return (Criteria) this;
        }

        public Criteria andImgKeyBetween(String value1, String value2) {
            addCriterion("img_key between", value1, value2, "imgKey");
            return (Criteria) this;
        }

        public Criteria andImgKeyNotBetween(String value1, String value2) {
            addCriterion("img_key not between", value1, value2, "imgKey");
            return (Criteria) this;
        }

        public Criteria andMediaUrl1IsNull() {
            addCriterion("media_url1 is null");
            return (Criteria) this;
        }

        public Criteria andMediaUrl1IsNotNull() {
            addCriterion("media_url1 is not null");
            return (Criteria) this;
        }

        public Criteria andMediaUrl1EqualTo(String value) {
            addCriterion("media_url1 =", value, "mediaUrl1");
            return (Criteria) this;
        }

        public Criteria andMediaUrl1NotEqualTo(String value) {
            addCriterion("media_url1 <>", value, "mediaUrl1");
            return (Criteria) this;
        }

        public Criteria andMediaUrl1GreaterThan(String value) {
            addCriterion("media_url1 >", value, "mediaUrl1");
            return (Criteria) this;
        }

        public Criteria andMediaUrl1GreaterThanOrEqualTo(String value) {
            addCriterion("media_url1 >=", value, "mediaUrl1");
            return (Criteria) this;
        }

        public Criteria andMediaUrl1LessThan(String value) {
            addCriterion("media_url1 <", value, "mediaUrl1");
            return (Criteria) this;
        }

        public Criteria andMediaUrl1LessThanOrEqualTo(String value) {
            addCriterion("media_url1 <=", value, "mediaUrl1");
            return (Criteria) this;
        }

        public Criteria andMediaUrl1Like(String value) {
            addCriterion("media_url1 like", value, "mediaUrl1");
            return (Criteria) this;
        }

        public Criteria andMediaUrl1NotLike(String value) {
            addCriterion("media_url1 not like", value, "mediaUrl1");
            return (Criteria) this;
        }

        public Criteria andMediaUrl1In(List<String> values) {
            addCriterion("media_url1 in", values, "mediaUrl1");
            return (Criteria) this;
        }

        public Criteria andMediaUrl1NotIn(List<String> values) {
            addCriterion("media_url1 not in", values, "mediaUrl1");
            return (Criteria) this;
        }

        public Criteria andMediaUrl1Between(String value1, String value2) {
            addCriterion("media_url1 between", value1, value2, "mediaUrl1");
            return (Criteria) this;
        }

        public Criteria andMediaUrl1NotBetween(String value1, String value2) {
            addCriterion("media_url1 not between", value1, value2, "mediaUrl1");
            return (Criteria) this;
        }

        public Criteria andMediaUrl2IsNull() {
            addCriterion("media_url2 is null");
            return (Criteria) this;
        }

        public Criteria andMediaUrl2IsNotNull() {
            addCriterion("media_url2 is not null");
            return (Criteria) this;
        }

        public Criteria andMediaUrl2EqualTo(String value) {
            addCriterion("media_url2 =", value, "mediaUrl2");
            return (Criteria) this;
        }

        public Criteria andMediaUrl2NotEqualTo(String value) {
            addCriterion("media_url2 <>", value, "mediaUrl2");
            return (Criteria) this;
        }

        public Criteria andMediaUrl2GreaterThan(String value) {
            addCriterion("media_url2 >", value, "mediaUrl2");
            return (Criteria) this;
        }

        public Criteria andMediaUrl2GreaterThanOrEqualTo(String value) {
            addCriterion("media_url2 >=", value, "mediaUrl2");
            return (Criteria) this;
        }

        public Criteria andMediaUrl2LessThan(String value) {
            addCriterion("media_url2 <", value, "mediaUrl2");
            return (Criteria) this;
        }

        public Criteria andMediaUrl2LessThanOrEqualTo(String value) {
            addCriterion("media_url2 <=", value, "mediaUrl2");
            return (Criteria) this;
        }

        public Criteria andMediaUrl2Like(String value) {
            addCriterion("media_url2 like", value, "mediaUrl2");
            return (Criteria) this;
        }

        public Criteria andMediaUrl2NotLike(String value) {
            addCriterion("media_url2 not like", value, "mediaUrl2");
            return (Criteria) this;
        }

        public Criteria andMediaUrl2In(List<String> values) {
            addCriterion("media_url2 in", values, "mediaUrl2");
            return (Criteria) this;
        }

        public Criteria andMediaUrl2NotIn(List<String> values) {
            addCriterion("media_url2 not in", values, "mediaUrl2");
            return (Criteria) this;
        }

        public Criteria andMediaUrl2Between(String value1, String value2) {
            addCriterion("media_url2 between", value1, value2, "mediaUrl2");
            return (Criteria) this;
        }

        public Criteria andMediaUrl2NotBetween(String value1, String value2) {
            addCriterion("media_url2 not between", value1, value2, "mediaUrl2");
            return (Criteria) this;
        }

        public Criteria andMediaUrl3IsNull() {
            addCriterion("media_url3 is null");
            return (Criteria) this;
        }

        public Criteria andMediaUrl3IsNotNull() {
            addCriterion("media_url3 is not null");
            return (Criteria) this;
        }

        public Criteria andMediaUrl3EqualTo(String value) {
            addCriterion("media_url3 =", value, "mediaUrl3");
            return (Criteria) this;
        }

        public Criteria andMediaUrl3NotEqualTo(String value) {
            addCriterion("media_url3 <>", value, "mediaUrl3");
            return (Criteria) this;
        }

        public Criteria andMediaUrl3GreaterThan(String value) {
            addCriterion("media_url3 >", value, "mediaUrl3");
            return (Criteria) this;
        }

        public Criteria andMediaUrl3GreaterThanOrEqualTo(String value) {
            addCriterion("media_url3 >=", value, "mediaUrl3");
            return (Criteria) this;
        }

        public Criteria andMediaUrl3LessThan(String value) {
            addCriterion("media_url3 <", value, "mediaUrl3");
            return (Criteria) this;
        }

        public Criteria andMediaUrl3LessThanOrEqualTo(String value) {
            addCriterion("media_url3 <=", value, "mediaUrl3");
            return (Criteria) this;
        }

        public Criteria andMediaUrl3Like(String value) {
            addCriterion("media_url3 like", value, "mediaUrl3");
            return (Criteria) this;
        }

        public Criteria andMediaUrl3NotLike(String value) {
            addCriterion("media_url3 not like", value, "mediaUrl3");
            return (Criteria) this;
        }

        public Criteria andMediaUrl3In(List<String> values) {
            addCriterion("media_url3 in", values, "mediaUrl3");
            return (Criteria) this;
        }

        public Criteria andMediaUrl3NotIn(List<String> values) {
            addCriterion("media_url3 not in", values, "mediaUrl3");
            return (Criteria) this;
        }

        public Criteria andMediaUrl3Between(String value1, String value2) {
            addCriterion("media_url3 between", value1, value2, "mediaUrl3");
            return (Criteria) this;
        }

        public Criteria andMediaUrl3NotBetween(String value1, String value2) {
            addCriterion("media_url3 not between", value1, value2, "mediaUrl3");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andMailIsNull() {
            addCriterion("mail is null");
            return (Criteria) this;
        }

        public Criteria andMailIsNotNull() {
            addCriterion("mail is not null");
            return (Criteria) this;
        }

        public Criteria andMailEqualTo(String value) {
            addCriterion("mail =", value, "mail");
            return (Criteria) this;
        }

        public Criteria andMailNotEqualTo(String value) {
            addCriterion("mail <>", value, "mail");
            return (Criteria) this;
        }

        public Criteria andMailGreaterThan(String value) {
            addCriterion("mail >", value, "mail");
            return (Criteria) this;
        }

        public Criteria andMailGreaterThanOrEqualTo(String value) {
            addCriterion("mail >=", value, "mail");
            return (Criteria) this;
        }

        public Criteria andMailLessThan(String value) {
            addCriterion("mail <", value, "mail");
            return (Criteria) this;
        }

        public Criteria andMailLessThanOrEqualTo(String value) {
            addCriterion("mail <=", value, "mail");
            return (Criteria) this;
        }

        public Criteria andMailLike(String value) {
            addCriterion("mail like", value, "mail");
            return (Criteria) this;
        }

        public Criteria andMailNotLike(String value) {
            addCriterion("mail not like", value, "mail");
            return (Criteria) this;
        }

        public Criteria andMailIn(List<String> values) {
            addCriterion("mail in", values, "mail");
            return (Criteria) this;
        }

        public Criteria andMailNotIn(List<String> values) {
            addCriterion("mail not in", values, "mail");
            return (Criteria) this;
        }

        public Criteria andMailBetween(String value1, String value2) {
            addCriterion("mail between", value1, value2, "mail");
            return (Criteria) this;
        }

        public Criteria andMailNotBetween(String value1, String value2) {
            addCriterion("mail not between", value1, value2, "mail");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLangIsNull() {
            addCriterion("lang is null");
            return (Criteria) this;
        }

        public Criteria andLangIsNotNull() {
            addCriterion("lang is not null");
            return (Criteria) this;
        }

        public Criteria andLangEqualTo(Integer value) {
            addCriterion("lang =", value, "lang");
            return (Criteria) this;
        }

        public Criteria andLangNotEqualTo(Integer value) {
            addCriterion("lang <>", value, "lang");
            return (Criteria) this;
        }

        public Criteria andLangGreaterThan(Integer value) {
            addCriterion("lang >", value, "lang");
            return (Criteria) this;
        }

        public Criteria andLangGreaterThanOrEqualTo(Integer value) {
            addCriterion("lang >=", value, "lang");
            return (Criteria) this;
        }

        public Criteria andLangLessThan(Integer value) {
            addCriterion("lang <", value, "lang");
            return (Criteria) this;
        }

        public Criteria andLangLessThanOrEqualTo(Integer value) {
            addCriterion("lang <=", value, "lang");
            return (Criteria) this;
        }

        public Criteria andLangIn(List<Integer> values) {
            addCriterion("lang in", values, "lang");
            return (Criteria) this;
        }

        public Criteria andLangNotIn(List<Integer> values) {
            addCriterion("lang not in", values, "lang");
            return (Criteria) this;
        }

        public Criteria andLangBetween(Integer value1, Integer value2) {
            addCriterion("lang between", value1, value2, "lang");
            return (Criteria) this;
        }

        public Criteria andLangNotBetween(Integer value1, Integer value2) {
            addCriterion("lang not between", value1, value2, "lang");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jc_homepage
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 06 14:42:09 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jc_homepage
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}