package cn.yx.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import cn.yx.entity.Demo;
import cn.yx.entity.DemoExample;


public interface DemoMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table demo
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    @Delete({ "delete from demo", "where id = #{id,jdbcType=BIGINT}" })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table demo
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    @Insert({ "insert into demo (id, author, ", "create_time, modify_time, ", "title, content, ",
            "parent, url, status)", "values (#{id,jdbcType=BIGINT}, #{author,jdbcType=VARCHAR}, ",
            "#{createTime,jdbcType=TIMESTAMP}, #{modifyTime,jdbcType=TIMESTAMP}, ",
            "#{title,jdbcType=VARCHAR}, #{content,jdbcType=VARCHAR}, ",
            "#{parent,jdbcType=INTEGER}, #{url,jdbcType=VARCHAR}, #{status,jdbcType=INTEGER})" })
    int insert(Demo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table demo
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    @InsertProvider(type = DemoSqlProvider.class, method = "insertSelective")
    int insertSelective(Demo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table demo
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    @SelectProvider(type = DemoSqlProvider.class, method = "selectByExample")
    @Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
            @Result(column = "author", property = "author", jdbcType = JdbcType.VARCHAR),
            @Result(column = "create_time", property = "createTime", jdbcType = JdbcType.TIMESTAMP),
            @Result(column = "modify_time", property = "modifyTime", jdbcType = JdbcType.TIMESTAMP),
            @Result(column = "title", property = "title", jdbcType = JdbcType.VARCHAR),
            @Result(column = "content", property = "content", jdbcType = JdbcType.VARCHAR),
            @Result(column = "parent", property = "parent", jdbcType = JdbcType.INTEGER),
            @Result(column = "url", property = "url", jdbcType = JdbcType.VARCHAR),
            @Result(column = "status", property = "status", jdbcType = JdbcType.INTEGER) })
    List<Demo> selectByExample(DemoExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table demo
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    @Select({ "select", "id, author, create_time, modify_time, title, content, parent, url, status", "from demo",
            "where id = #{id,jdbcType=BIGINT}" })
    @Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
            @Result(column = "author", property = "author", jdbcType = JdbcType.VARCHAR),
            @Result(column = "create_time", property = "createTime", jdbcType = JdbcType.TIMESTAMP),
            @Result(column = "modify_time", property = "modifyTime", jdbcType = JdbcType.TIMESTAMP),
            @Result(column = "title", property = "title", jdbcType = JdbcType.VARCHAR),
            @Result(column = "content", property = "content", jdbcType = JdbcType.VARCHAR),
            @Result(column = "parent", property = "parent", jdbcType = JdbcType.INTEGER),
            @Result(column = "url", property = "url", jdbcType = JdbcType.VARCHAR),
            @Result(column = "status", property = "status", jdbcType = JdbcType.INTEGER) })
    Demo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table demo
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    @UpdateProvider(type = DemoSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Demo record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table demo
     * @mbg.generated  Mon Nov 06 14:42:09 CST 2017
     */
    @Update({ "update demo", "set author = #{author,jdbcType=VARCHAR},",
            "create_time = #{createTime,jdbcType=TIMESTAMP},", "modify_time = #{modifyTime,jdbcType=TIMESTAMP},",
            "title = #{title,jdbcType=VARCHAR},", "content = #{content,jdbcType=VARCHAR},",
            "parent = #{parent,jdbcType=INTEGER},", "url = #{url,jdbcType=VARCHAR},",
            "status = #{status,jdbcType=INTEGER}", "where id = #{id,jdbcType=BIGINT}" })
    int updateByPrimaryKey(Demo record);
}