package cn.yx.mapper;

import cn.yx.entity.JcAbout;
import cn.yx.entity.JcAboutExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface JcAboutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_about
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    @Delete({
        "delete from jc_about",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_about
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    @Insert({
        "insert into jc_about (id, parent, ",
        "img_key, status, ",
        "create_time, lang, ",
        "content)",
        "values (#{id,jdbcType=INTEGER}, #{parent,jdbcType=INTEGER}, ",
        "#{imgKey,jdbcType=VARCHAR}, #{status,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{lang,jdbcType=INTEGER}, ",
        "#{content,jdbcType=LONGVARCHAR})"
    })
    int insert(JcAbout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_about
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    @InsertProvider(type=JcAboutSqlProvider.class, method="insertSelective")
    int insertSelective(JcAbout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_about
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    @SelectProvider(type=JcAboutSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="parent", property="parent", jdbcType=JdbcType.INTEGER),
        @Result(column="img_key", property="imgKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="lang", property="lang", jdbcType=JdbcType.INTEGER),
        @Result(column="content", property="content", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<JcAbout> selectByExampleWithBLOBs(JcAboutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_about
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    @SelectProvider(type=JcAboutSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="parent", property="parent", jdbcType=JdbcType.INTEGER),
        @Result(column="img_key", property="imgKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="lang", property="lang", jdbcType=JdbcType.INTEGER)
    })
    List<JcAbout> selectByExample(JcAboutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_about
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    @Select({
        "select",
        "id, parent, img_key, status, create_time, lang, content",
        "from jc_about",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="parent", property="parent", jdbcType=JdbcType.INTEGER),
        @Result(column="img_key", property="imgKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="lang", property="lang", jdbcType=JdbcType.INTEGER),
        @Result(column="content", property="content", jdbcType=JdbcType.LONGVARCHAR)
    })
    JcAbout selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_about
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    @UpdateProvider(type=JcAboutSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(JcAbout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_about
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    @Update({
        "update jc_about",
        "set parent = #{parent,jdbcType=INTEGER},",
          "img_key = #{imgKey,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "lang = #{lang,jdbcType=INTEGER},",
          "content = #{content,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(JcAbout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_about
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    @Update({
        "update jc_about",
        "set parent = #{parent,jdbcType=INTEGER},",
          "img_key = #{imgKey,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "lang = #{lang,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(JcAbout record);
}