package cn.yx.mapper;

import cn.yx.entity.JcBanner;
import cn.yx.entity.JcBannerExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface JcBannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_banner
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    @Delete({
        "delete from jc_banner",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_banner
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    @Insert({
        "insert into jc_banner (id, title, ",
        "img_key, url, status, ",
        "create_time, lang)",
        "values (#{id,jdbcType=INTEGER}, #{title,jdbcType=VARCHAR}, ",
        "#{imgKey,jdbcType=VARCHAR}, #{url,jdbcType=VARCHAR}, #{status,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{lang,jdbcType=INTEGER})"
    })
    int insert(JcBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_banner
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    @InsertProvider(type=JcBannerSqlProvider.class, method="insertSelective")
    int insertSelective(JcBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_banner
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    @SelectProvider(type=JcBannerSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="img_key", property="imgKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="lang", property="lang", jdbcType=JdbcType.INTEGER)
    })
    List<JcBanner> selectByExample(JcBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_banner
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    @Select({
        "select",
        "id, title, img_key, url, status, create_time, lang",
        "from jc_banner",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="img_key", property="imgKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="lang", property="lang", jdbcType=JdbcType.INTEGER)
    })
    JcBanner selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_banner
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    @UpdateProvider(type=JcBannerSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(JcBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_banner
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    @Update({
        "update jc_banner",
        "set title = #{title,jdbcType=VARCHAR},",
          "img_key = #{imgKey,jdbcType=VARCHAR},",
          "url = #{url,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "lang = #{lang,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(JcBanner record);
}