package cn.yx.mapper;

import cn.yx.entity.JcContact;
import cn.yx.entity.JcContactExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface JcContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_contact
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    @Delete({
        "delete from jc_contact",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_contact
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    @Insert({
        "insert into jc_contact (id, title, ",
        "parent, img_key, ",
        "browes, author, status, ",
        "create_time, lang, ",
        "content)",
        "values (#{id,jdbcType=INTEGER}, #{title,jdbcType=VARCHAR}, ",
        "#{parent,jdbcType=INTEGER}, #{imgKey,jdbcType=VARCHAR}, ",
        "#{browes,jdbcType=BIGINT}, #{author,jdbcType=VARCHAR}, #{status,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{lang,jdbcType=INTEGER}, ",
        "#{content,jdbcType=LONGVARCHAR})"
    })
    int insert(JcContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_contact
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    @InsertProvider(type=JcContactSqlProvider.class, method="insertSelective")
    int insertSelective(JcContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_contact
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    @SelectProvider(type=JcContactSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="parent", property="parent", jdbcType=JdbcType.INTEGER),
        @Result(column="img_key", property="imgKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="browes", property="browes", jdbcType=JdbcType.BIGINT),
        @Result(column="author", property="author", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="lang", property="lang", jdbcType=JdbcType.INTEGER),
        @Result(column="content", property="content", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<JcContact> selectByExampleWithBLOBs(JcContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_contact
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    @SelectProvider(type=JcContactSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="parent", property="parent", jdbcType=JdbcType.INTEGER),
        @Result(column="img_key", property="imgKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="browes", property="browes", jdbcType=JdbcType.BIGINT),
        @Result(column="author", property="author", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="lang", property="lang", jdbcType=JdbcType.INTEGER)
    })
    List<JcContact> selectByExample(JcContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_contact
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    @Select({
        "select",
        "id, title, parent, img_key, browes, author, status, create_time, lang, content",
        "from jc_contact",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="parent", property="parent", jdbcType=JdbcType.INTEGER),
        @Result(column="img_key", property="imgKey", jdbcType=JdbcType.VARCHAR),
        @Result(column="browes", property="browes", jdbcType=JdbcType.BIGINT),
        @Result(column="author", property="author", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="lang", property="lang", jdbcType=JdbcType.INTEGER),
        @Result(column="content", property="content", jdbcType=JdbcType.LONGVARCHAR)
    })
    JcContact selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_contact
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    @UpdateProvider(type=JcContactSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(JcContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_contact
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    @Update({
        "update jc_contact",
        "set title = #{title,jdbcType=VARCHAR},",
          "parent = #{parent,jdbcType=INTEGER},",
          "img_key = #{imgKey,jdbcType=VARCHAR},",
          "browes = #{browes,jdbcType=BIGINT},",
          "author = #{author,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "lang = #{lang,jdbcType=INTEGER},",
          "content = #{content,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(JcContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jc_contact
     *
     * @mbg.generated Mon Nov 06 14:42:09 CST 2017
     */
    @Update({
        "update jc_contact",
        "set title = #{title,jdbcType=VARCHAR},",
          "parent = #{parent,jdbcType=INTEGER},",
          "img_key = #{imgKey,jdbcType=VARCHAR},",
          "browes = #{browes,jdbcType=BIGINT},",
          "author = #{author,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "lang = #{lang,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(JcContact record);
}