package cn.yx.mapper;

import cn.yx.entity.JcCulture;
import cn.yx.entity.JcCultureExample;
import cn.yx.entity.JcCultureWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface JcCultureMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table jc_culture
     * @mbg.generated  Tue Nov 07 09:49:08 CST 2017
     */
    @Delete({ "delete from jc_culture", "where id = #{id,jdbcType=INTEGER}" })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table jc_culture
     * @mbg.generated  Tue Nov 07 09:49:08 CST 2017
     */
    @Insert({ "insert into jc_culture (id, parent, ", "title, img_key, content, ", "status, create_time, ", "lang)",
            "values (#{id,jdbcType=INTEGER}, #{parent,jdbcType=INTEGER}, ",
            "#{title,jdbcType=VARCHAR}, #{imgKey,jdbcType=VARCHAR}, #{content,jdbcType=VARCHAR}, ",
            "#{status,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ", "#{lang,jdbcType=INTEGER})" })
    int insert(JcCulture record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table jc_culture
     * @mbg.generated  Tue Nov 07 09:49:08 CST 2017
     */
    @InsertProvider(type = JcCultureSqlProvider.class, method = "insertSelective")
    int insertSelective(JcCulture record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table jc_culture
     * @mbg.generated  Tue Nov 07 09:49:08 CST 2017
     */
    @SelectProvider(type = JcCultureSqlProvider.class, method = "selectByExample")
    @Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "parent", property = "parent", jdbcType = JdbcType.INTEGER),
            @Result(column = "title", property = "title", jdbcType = JdbcType.VARCHAR),
            @Result(column = "img_key", property = "imgKey", jdbcType = JdbcType.VARCHAR),
            @Result(column = "content", property = "content", jdbcType = JdbcType.VARCHAR),
            @Result(column = "status", property = "status", jdbcType = JdbcType.INTEGER),
            @Result(column = "create_time", property = "createTime", jdbcType = JdbcType.TIMESTAMP),
            @Result(column = "lang", property = "lang", jdbcType = JdbcType.INTEGER) })
    List<JcCulture> selectByExample(JcCultureExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table jc_culture
     * @mbg.generated  Tue Nov 07 09:49:08 CST 2017
     */
    @Select({ "select", "id, parent, title, img_key, content, status, create_time, lang", "from jc_culture",
            "where id = #{id,jdbcType=INTEGER}" })
    @Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "parent", property = "parent", jdbcType = JdbcType.INTEGER),
            @Result(column = "title", property = "title", jdbcType = JdbcType.VARCHAR),
            @Result(column = "img_key", property = "imgKey", jdbcType = JdbcType.VARCHAR),
            @Result(column = "content", property = "content", jdbcType = JdbcType.VARCHAR),
            @Result(column = "status", property = "status", jdbcType = JdbcType.INTEGER),
            @Result(column = "create_time", property = "createTime", jdbcType = JdbcType.TIMESTAMP),
            @Result(column = "lang", property = "lang", jdbcType = JdbcType.INTEGER) })
    JcCulture selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table jc_culture
     * @mbg.generated  Tue Nov 07 09:49:08 CST 2017
     */
    @UpdateProvider(type = JcCultureSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(JcCulture record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table jc_culture
     * @mbg.generated  Tue Nov 07 09:49:08 CST 2017
     */
    @Update({ "update jc_culture", "set parent = #{parent,jdbcType=INTEGER},", "title = #{title,jdbcType=VARCHAR},",
            "img_key = #{imgKey,jdbcType=VARCHAR},", "content = #{content,jdbcType=VARCHAR},",
            "status = #{status,jdbcType=INTEGER},", "create_time = #{createTime,jdbcType=TIMESTAMP},",
            "lang = #{lang,jdbcType=INTEGER}", "where id = #{id,jdbcType=INTEGER}" })
    int updateByPrimaryKey(JcCulture record);
}