package cn.yx.mapper;

import cn.yx.entity.JcHomepage;
import cn.yx.entity.JcHomepageExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface JcHomepageMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table jc_homepage
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    @Delete({ "delete from jc_homepage", "where id = #{id,jdbcType=INTEGER}" })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table jc_homepage
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    @Insert({ "insert into jc_homepage (id, video_url, ", "introduction, img_key, ", "media_key, media_url, ",
            "address, phone, ", "mail, status, create_time, ", "lang)",
            "values (#{id,jdbcType=INTEGER}, #{videoUrl,jdbcType=VARCHAR}, ",
            "#{introduction,jdbcType=VARCHAR}, #{imgKey,jdbcType=VARCHAR}, ",
            "#{mediaKey,jdbcType=VARCHAR}, #{mediaUrl,jdbcType=VARCHAR}, ",
            "#{address,jdbcType=VARCHAR}, #{phone,jdbcType=VARCHAR}, ",
            "#{mail,jdbcType=VARCHAR}, #{status,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
            "#{lang,jdbcType=INTEGER})" })
    int insert(JcHomepage record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table jc_homepage
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    @InsertProvider(type = JcHomepageSqlProvider.class, method = "insertSelective")
    int insertSelective(JcHomepage record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table jc_homepage
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    @SelectProvider(type = JcHomepageSqlProvider.class, method = "selectByExample")
    @Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "video_url", property = "videoUrl", jdbcType = JdbcType.VARCHAR),
            @Result(column = "introduction", property = "introduction", jdbcType = JdbcType.VARCHAR),
            @Result(column = "img_key", property = "imgKey", jdbcType = JdbcType.VARCHAR),
            @Result(column = "media_key", property = "mediaKey", jdbcType = JdbcType.VARCHAR),
            @Result(column = "media_url", property = "mediaUrl", jdbcType = JdbcType.VARCHAR),
            @Result(column = "address", property = "address", jdbcType = JdbcType.VARCHAR),
            @Result(column = "phone", property = "phone", jdbcType = JdbcType.VARCHAR),
            @Result(column = "mail", property = "mail", jdbcType = JdbcType.VARCHAR),
            @Result(column = "status", property = "status", jdbcType = JdbcType.INTEGER),
            @Result(column = "create_time", property = "createTime", jdbcType = JdbcType.TIMESTAMP),
            @Result(column = "lang", property = "lang", jdbcType = JdbcType.INTEGER) })
    List<JcHomepage> selectByExample(JcHomepageExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table jc_homepage
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    @Select({ "select", "id, video_url, introduction, img_key, media_key, media_url, address, phone, ",
            "mail, status, create_time, lang", "from jc_homepage", "where id = #{id,jdbcType=INTEGER}" })
    @Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "video_url", property = "videoUrl", jdbcType = JdbcType.VARCHAR),
            @Result(column = "introduction", property = "introduction", jdbcType = JdbcType.VARCHAR),
            @Result(column = "img_key", property = "imgKey", jdbcType = JdbcType.VARCHAR),
            @Result(column = "media_key", property = "mediaKey", jdbcType = JdbcType.VARCHAR),
            @Result(column = "media_url", property = "mediaUrl", jdbcType = JdbcType.VARCHAR),
            @Result(column = "address", property = "address", jdbcType = JdbcType.VARCHAR),
            @Result(column = "phone", property = "phone", jdbcType = JdbcType.VARCHAR),
            @Result(column = "mail", property = "mail", jdbcType = JdbcType.VARCHAR),
            @Result(column = "status", property = "status", jdbcType = JdbcType.INTEGER),
            @Result(column = "create_time", property = "createTime", jdbcType = JdbcType.TIMESTAMP),
            @Result(column = "lang", property = "lang", jdbcType = JdbcType.INTEGER) })
    JcHomepage selectByPrimaryKey(Integer id);

    @Select({ "select", " address, phone, mail, lang", "from jc_homepage", "where lang = #{lang,jdbcType=INTEGER} order by create_time desc limit 1" })
    JcHomepage getFooter(Integer lang);
    

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table jc_homepage
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    @UpdateProvider(type = JcHomepageSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(JcHomepage record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table jc_homepage
     * @mbg.generated  Tue Nov 07 10:03:26 CST 2017
     */
    @Update({ "update jc_homepage", "set video_url = #{videoUrl,jdbcType=VARCHAR},",
            "introduction = #{introduction,jdbcType=VARCHAR},", "img_key = #{imgKey,jdbcType=VARCHAR},",
            "media_key = #{mediaKey,jdbcType=VARCHAR},", "media_url = #{mediaUrl,jdbcType=VARCHAR},",
            "address = #{address,jdbcType=VARCHAR},", "phone = #{phone,jdbcType=VARCHAR},",
            "mail = #{mail,jdbcType=VARCHAR},", "status = #{status,jdbcType=INTEGER},",
            "create_time = #{createTime,jdbcType=TIMESTAMP},", "lang = #{lang,jdbcType=INTEGER}",
            "where id = #{id,jdbcType=INTEGER}" })
    int updateByPrimaryKey(JcHomepage record);
}